const { DefinePlugin } = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

const { NODE_ENV = 'testing' } = process.env; // Mimic the @architect behaviour.
const DEV = NODE_ENV !== 'production';
const PROD = NODE_ENV === 'production';
const DIST_FOLDER = path.join(
  __dirname,
  'src',
  'http',
  'get-assets-000file',
  'files'
);
const LIB_FOLDER = path.join(__dirname, 'lib');
const SCRIPTS_FOLDER = path.join(LIB_FOLDER, 'scripts');
const STYLES_FOLDER = path.join(LIB_FOLDER, 'styles');

const LAYOUT_BANNER = `/*###################################################
#                                                   #
#   CAUTION!! THIS FILE WAS GENERATED BY WEBPACK!   #
#                                                   #
# If you want to apply changes, go to ./lib/layout/ #
#                                                   #
###################################################*/`;

const jsFileName = DEV ? `[name].js` : `[name].[chunkhash:6].js`;
const cssFileName = DEV ? `[name].css` : `[name].[chunkhash:6].css`;
const mode = DEV ? 'development' : 'production';

const optimization = {
  namedModules: false,
  namedChunks: false,
  nodeEnv: 'production',
  flagIncludedChunks: true,
  occurrenceOrder: true,
  sideEffects: true,
  usedExports: true,
  concatenateModules: true,
  splitChunks: {
    hidePathInfo: true,
    minSize: 30000,
    maxAsyncRequests: 5,
    maxInitialRequests: 3,
  },
  noEmitOnErrors: true,
  checkWasmTypes: true,
  minimize: true,
  minimizer: [
    new UglifyJsPlugin({
      exclude: /\/layout/,
    }),
  ],
};

const babelPlugins = [
  '@babel/plugin-proposal-class-properties',
  '@babel/plugin-syntax-dynamic-import',
  [
    '@babel/plugin-transform-runtime',
    {
      regenerator: true,
    },
  ],
];

if (PROD) {
  babelPlugins.unshift([
    'transform-react-remove-prop-types',
    {
      mode: 'wrap',
      ignoreFilenames: ['node_modules'],
    },
  ]);
}

const config = {
  mode,

  devtool: 'cheap-module-eval-source-map',

  entry: {
    admin: path.resolve(SCRIPTS_FOLDER, 'admin', 'index.js'),
    main: path.resolve(STYLES_FOLDER, 'main.css'),
    blog: path.resolve(SCRIPTS_FOLDER, 'blog', 'index.js'),
  },

  output: {
    filename: jsFileName,
    path: DIST_FOLDER,
    publicPath: '/assets/',
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env', '@babel/preset-react'],
            plugins: babelPlugins,
          },
        },
      },
      {
        test: /\.css$/,
        oneOf: [
          {
            test: /lib\/styles\//,
            use: [
              {
                loader: MiniCssExtractPlugin.loader,
                options: {
                  publicPath: '../',
                },
              },
              {
                loader: 'css-loader',
                options: { importLoaders: 1 },
              },
              'postcss-loader',
            ],
          },
          {
            test: /lib\/scripts\//,
            use: [
              {
                loader: MiniCssExtractPlugin.loader,
                options: {
                  publicPath: '../',
                },
              },
              {
                loader: 'css-loader',
                options: {
                  modules: true,
                  localIdentName: '[hash:base64:8]',
                  importLoaders: 1,
                },
              },
              'postcss-loader',
            ],
          },
        ],
      },
    ],
  },

  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
    'react-dom/server': 'ReactDOMServer',
    'react-router-dom': 'ReactRouterDOM',
    'react-ace': 'ReactAce',
  },

  plugins: [
    new MiniCssExtractPlugin({
      filename: cssFileName,
    }),
    new HtmlWebpackPlugin({
      filename: '../../../views/layouts/admin.js',
      template: path.resolve(
        __dirname,
        path.join('lib', 'layout', 'admin.ejs')
      ),
      inject: false,
      LAYOUT_BANNER,
    }),
    new HtmlWebpackPlugin({
      filename: '../../../views/layouts/blog.js',
      template: path.resolve(__dirname, path.join('lib', 'layout', 'blog.ejs')),
      inject: false,
      LAYOUT_BANNER,
    }),
    new DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(NODE_ENV),
    }),
  ],
};

if (!DEV) {
  config.optimization = optimization;
}

module.exports = config;
